name: Terraform CI/CD

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.13.3

defaults:
  run:
    shell: bash
    #working-directory: main.tf

jobs:
  preview:
    name: "preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: configure aws credential
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: init # init -upgradeをすることにより、GitHub Actions 上でも AWS Providerの最新化ができる
        run: |
          terraform init -no-color -upgrade

      - name: validate
        run: |
          terraform validate -no-color

      - name: plan
        run: |
          terraform plan

      - name: apply
        timeout-minutes: 1  # 120分でタイムアウト
        run: |
          terraform apply -auto-approve

      - name: always destroy
        if: always()
        run: | 
          terraform destroy -auto-approve

#      - name: only success destroy
#        if: success()
#        run: | 
#          terraform destroy -auto-approve

#      - name: only failure destroy
#        if: failure()
#        run: | 
#          terraform destroy -auto-approve         
